export type PlanStatus = "Published" | "Draft" | "Archived";

export type PlanImage = {
  id: string;
  url: string;
  alt?: string;
  title?: string;
};

export type PlanScores = {
  functionality: number;
  comfort: number;
  constructionSimplicity: number;
  costEfficiency: number;
  hotClimateAdaptation: number;
  futureExtension: number;
  naturalVentilation?: number;
  familySuitability?: number;
};

export type Plan = {
  id: string;
  title: string;
  slug: string;
  reference: string;
  shortDescription: string;
  description: string;
  category: string;
  tags?: string[];
  totalArea: number;
  builtArea: number;
  livingArea?: number;
  plotWidth: number;
  plotLength: number;
  minPlotWidth?: number;
  minPlotLength?: number;
  minimumPlotWidth?: number;
  minimumPlotLength?: number;
  bedrooms: number;
  bathrooms: number;
  livingRooms: number;
  kitchens: number;
  floors: number;
  roofType: string;
  architecturalStyle: string;
  foundationType: string;
  structureType: string;
  constructionDifficulty?: "Easy" | "Medium" | "Advanced";
  climateTags?: string[];
  specialFeatures?: string[];
  features?: string[];
  mainImage: string;
  galleryImages: string[];
  images?: PlanImage[];
  floorPlanImage?: string;
  elevationImage?: string;
  threeDViewImage?: string;
  threeDImage?: string;
  cadPreviewImage?: string;
  revitPreviewImage?: string;
  openGraphImage?: string;
  mainImageAlt?: string;
  galleryImageAlt?: string;
  freePackEnabled: boolean;
  premiumPackEnabled: boolean;
  cadPackEnabled: boolean;
  freePdfUrl: string;
  premiumUrl: string;
  cadUrl: string;
  premiumPdfUrl?: string;
  premiumZipUrl?: string;
  dwgFileUrl?: string;
  revitFileUrl?: string;
  ifcFileUrl?: string;
  cadZipUrl?: string;
  premiumPrice: number;
  cadPrice: number;
  oldPremiumPrice?: number;
  oldCadPrice?: number;
  currency?: string;
  freePackDescription?: string;
  premiumPackDescription?: string;
  cadPackDescription?: string;
  isWatermarked?: boolean;
  premiumIncludedFiles?: string[];
  cadIncludedFiles?: string[];
  badges: string[];
  scores: PlanScores;
  bestFor: string[];
  beCareful: string[];
  mainStrengths?: string[];
  mainLimitations?: string[];
  recommendedUsers?: string[];
  constructionNotes?: string;
  climateNotes?: string;
  futureExtensionNotes?: string;
  seoTitle?: string;
  seoDescription?: string;
  metaDescription?: string;
  seoKeywords?: string[];
  canonicalUrl?: string;
  focusKeyword?: string;
  secondaryKeywords?: string[];
  seoScore?: number;
  readinessScore?: number;
  smartScore?: number;
  priorityScore?: number;
  manualRank?: number;
  categoryRank?: number;
  homepageRank?: number;
  publishedAt?: string;
  showOnHomepage?: boolean;
  showInCategory?: boolean;
  downloads?: number;
  premiumClicks?: number;
  cadClicks?: number;
  updatedDate?: string;
  createdAt?: string;
  updatedAt?: string;
  featured?: boolean;
  popular?: boolean;
  isNew?: boolean;
  faq?: Array<{ question: string; answer: string }>;
  status: PlanStatus;
  views: number;
};
