import type { Plan } from "@/types/plan";
import { calculatePriorityScore, calculateSmartScore } from "@/lib/planRanking";
import { getPlanSeoScore, getReadinessScore } from "@/lib/adminMetrics";

const planImage = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

const defaultFaq = [
  { question: "What professional review is required?", answer: "A qualified local architect, engineer or other authorized professional must adapt the concept to the site, regulations, soil and project requirements before construction." },
  { question: "What is included in the free PDF?", answer: "The free preview includes a watermarked plan overview and key dimensions for early review." },
  { question: "What is included in the premium PDF pack?", answer: "Premium packs include complete PDF drawings such as plans, elevations, sections and construction notes when available." },
  { question: "What is the difference between PDF, DWG, Revit and IFC?", answer: "PDF is for viewing, DWG is editable CAD, Revit is a BIM model and IFC is an exchange format." },
  { question: "Can this plan be modified?", answer: "Yes, but modifications should be handled by a qualified local professional." }
];

const premiumFiles = ["Complete PDF", "Floor plans", "Elevations", "Sections", "Roof plan", "Metric version", "Imperial version"];
const cadFiles = ["DWG", "Revit RVT", "IFC", "Complete PDF", "3D images", "Editable source files", "Metric version"];

const basePlans: Plan[] = [
  {
    id: "plan-001",
    title: "Modern 3 Bedroom House Plan for 20x20m / 66x66 ft Plot",
    slug: "modern-3-bedroom-house-plan-20x20m-plot",
    reference: "MFHP-001/2026",
    shortDescription: "A bright family home with open living, shaded terrace and practical zoning for warm climates.",
    description: "This modern 3 bedroom house plan is designed for families who want a polished home that remains realistic to build. The layout balances privacy, natural ventilation, easy circulation and a generous living area connected to the terrace.",
    category: "Modern House Plans",
    totalArea: 168,
    builtArea: 142,
    plotWidth: 20,
    plotLength: 20,
    bedrooms: 3,
    bathrooms: 3,
    livingRooms: 1,
    kitchens: 1,
    floors: 1,
    roofType: "Flat roof",
    architecturalStyle: "Modern tropical",
    foundationType: "Reinforced concrete strip foundation",
    structureType: "Concrete frame and block walls",
    mainImage: planImage("photo-1600607687939-ce8a6c25118c"),
    galleryImages: [planImage("photo-1600607687644-c7171b42498b"), planImage("photo-1600585154340-be6161a56a0c")],
    freePackEnabled: true,
    premiumPackEnabled: true,
    cadPackEnabled: true,
    freePdfUrl: "#",
    premiumUrl: "#",
    cadUrl: "#",
    premiumPrice: 9.99,
    cadPrice: 39.99,
    badges: ["Free Preview", "Premium PDF", "DWG", "Revit", "Hot Climate Friendly", "Future Extension Ready"],
    scores: { functionality: 92, comfort: 90, constructionSimplicity: 84, costEfficiency: 82, hotClimateAdaptation: 94, futureExtension: 86 },
    bestFor: ["Medium family", "Hot climate", "20x20m / 66x66 ft plot", "Moderate construction budget"],
    beCareful: ["Not ideal for very narrow plots", "Future extension may require structural review"],
    status: "Published",
    views: 12840
  },
  {
    id: "plan-002",
    title: "Small 2 Bedroom House Plan with Terrace",
    slug: "small-2-bedroom-house-plan-with-terrace",
    reference: "MFHP-002/2026",
    shortDescription: "A compact home with a welcoming terrace, efficient rooms and simple construction logic.",
    description: "Designed for first homes, guest houses and small families, this plan keeps construction controlled without feeling cramped. The terrace extends the living space and improves shade.",
    category: "Small House Plans",
    totalArea: 86,
    builtArea: 74,
    plotWidth: 12,
    plotLength: 18,
    bedrooms: 2,
    bathrooms: 2,
    livingRooms: 1,
    kitchens: 1,
    floors: 1,
    roofType: "Hip roof",
    architecturalStyle: "Contemporary compact",
    foundationType: "Strip foundation",
    structureType: "Block wall construction",
    mainImage: planImage("photo-1600566753190-17f0baa2a6c3"),
    galleryImages: [planImage("photo-1600573472592-401b489a3cdc"), planImage("photo-1600566752355-35792bedcfea")],
    freePackEnabled: true,
    premiumPackEnabled: true,
    cadPackEnabled: false,
    freePdfUrl: "#",
    premiumUrl: "#",
    cadUrl: "#",
    premiumPrice: 7.99,
    cadPrice: 0,
    badges: ["Free Preview", "Premium PDF", "Low Cost", "With Terrace"],
    scores: { functionality: 86, comfort: 80, constructionSimplicity: 93, costEfficiency: 95, hotClimateAdaptation: 84, futureExtension: 72 },
    bestFor: ["Small family", "Starter home", "Low cost construction", "Rental compound"],
    beCareful: ["Limited storage", "Future floor addition needs engineer review"],
    status: "Published",
    views: 9340
  },
  {
    id: "plan-003",
    title: "Low Cost Family House Plan",
    slug: "low-cost-family-house-plan",
    reference: "MFHP-003/2026",
    shortDescription: "A cost-aware family plan with regular spans, simple roof geometry and flexible rooms.",
    description: "This plan focuses on buildability and budget control. It uses practical room sizes, fewer structural complications and a clean rectangular footprint.",
    category: "Low Cost House Plans",
    totalArea: 118,
    builtArea: 104,
    plotWidth: 15,
    plotLength: 20,
    bedrooms: 3,
    bathrooms: 2,
    livingRooms: 1,
    kitchens: 1,
    floors: 1,
    roofType: "Gable roof",
    architecturalStyle: "Simple contemporary",
    foundationType: "Strip foundation",
    structureType: "Load-bearing block walls",
    mainImage: planImage("photo-1600047509807-ba8f99d2cdde"),
    galleryImages: [planImage("photo-1600607688969-a5bfcd646154"), planImage("photo-1600566753086-00f18fb6b3ea")],
    freePackEnabled: true,
    premiumPackEnabled: true,
    cadPackEnabled: true,
    freePdfUrl: "#",
    premiumUrl: "#",
    cadUrl: "#",
    premiumPrice: 8.99,
    cadPrice: 29.99,
    badges: ["Free Preview", "Premium PDF", "DWG", "Low Cost"],
    scores: { functionality: 84, comfort: 78, constructionSimplicity: 96, costEfficiency: 96, hotClimateAdaptation: 80, futureExtension: 78 },
    bestFor: ["Budget builders", "Phased construction", "Simple local construction teams"],
    beCareful: ["Facade can be upgraded later", "Room sizes are efficient, not oversized"],
    status: "Published",
    views: 15620
  },
  {
    id: "plan-004",
    title: "Modern 4 Bedroom House Plan with Courtyard",
    slug: "modern-4-bedroom-house-plan-with-courtyard",
    reference: "MFHP-004/2026",
    shortDescription: "A refined family villa organized around a private courtyard for light and airflow.",
    description: "A premium layout for families that want privacy, daylight and an elegant arrival experience. The courtyard improves cross ventilation and creates a calm internal focus.",
    category: "4 Bedroom House Plans",
    totalArea: 244,
    builtArea: 216,
    plotWidth: 25,
    plotLength: 30,
    bedrooms: 4,
    bathrooms: 4,
    livingRooms: 2,
    kitchens: 1,
    floors: 1,
    roofType: "Flat roof",
    architecturalStyle: "Modern courtyard villa",
    foundationType: "Reinforced raft foundation",
    structureType: "Concrete frame",
    mainImage: planImage("photo-1600607687920-4e2a09cf159d"),
    galleryImages: [planImage("photo-1600607688066-890987f18a86"), planImage("photo-1600566753151-384129cf4e3e")],
    freePackEnabled: false,
    premiumPackEnabled: true,
    cadPackEnabled: true,
    freePdfUrl: "#",
    premiumUrl: "#",
    cadUrl: "#",
    premiumPrice: 14.99,
    cadPrice: 49.99,
    badges: ["Premium PDF", "DWG", "Revit", "IFC", "Hot Climate Friendly"],
    scores: { functionality: 94, comfort: 95, constructionSimplicity: 76, costEfficiency: 70, hotClimateAdaptation: 92, futureExtension: 80 },
    bestFor: ["Large family", "Premium residence", "Wide plots", "Courtyard living"],
    beCareful: ["Higher construction budget", "Requires careful drainage planning"],
    status: "Published",
    views: 7320
  },
  {
    id: "plan-005",
    title: "Compact House Plan for 20x10m / 66x33 ft Plot",
    slug: "compact-house-plan-20x10m-plot",
    reference: "MFHP-005/2026",
    shortDescription: "A narrow-plot plan with clear circulation and no wasted rooms.",
    description: "Created for long narrow plots, this compact house keeps living spaces bright while respecting practical setbacks and a straightforward structure.",
    category: "20x10m / 66x33 ft Plot House Plans",
    totalArea: 102,
    builtArea: 90,
    plotWidth: 10,
    plotLength: 20,
    bedrooms: 3,
    bathrooms: 2,
    livingRooms: 1,
    kitchens: 1,
    floors: 1,
    roofType: "Shed roof",
    architecturalStyle: "Urban compact",
    foundationType: "Strip foundation",
    structureType: "Concrete block",
    mainImage: planImage("photo-1600585154526-990dced4db0d"),
    galleryImages: [planImage("photo-1600585152915-d208bec867a1"), planImage("photo-1600566752229-250ed79470f8")],
    freePackEnabled: true,
    premiumPackEnabled: true,
    cadPackEnabled: false,
    freePdfUrl: "#",
    premiumUrl: "#",
    cadUrl: "#",
    premiumPrice: 8.99,
    cadPrice: 0,
    badges: ["Free Preview", "Premium PDF", "20x10m / 66x33 ft Plot", "Low Cost"],
    scores: { functionality: 82, comfort: 76, constructionSimplicity: 89, costEfficiency: 88, hotClimateAdaptation: 78, futureExtension: 70 },
    bestFor: ["Narrow plots", "Urban infill", "Small families"],
    beCareful: ["Check side setbacks", "Ventilation depends on site openings"],
    status: "Draft",
    views: 4210
  },
  {
    id: "plan-006",
    title: "African Family House Plan with Veranda",
    slug: "african-family-house-plan-with-veranda",
    reference: "MFHP-006/2026",
    shortDescription: "A family home shaped for veranda living, shade and practical everyday routines.",
    description: "This plan blends contemporary organization with familiar African family living patterns. The veranda supports social life, shade and outdoor work areas.",
    category: "African House Plans",
    totalArea: 156,
    builtArea: 132,
    plotWidth: 18,
    plotLength: 25,
    bedrooms: 3,
    bathrooms: 3,
    livingRooms: 1,
    kitchens: 1,
    floors: 1,
    roofType: "Hip roof",
    architecturalStyle: "African contemporary",
    foundationType: "Strip foundation",
    structureType: "Concrete frame and masonry",
    mainImage: planImage("photo-1600585153490-76fb20a32601"),
    galleryImages: [planImage("photo-1600566752734-20a0ef0a2e07"), planImage("photo-1600585154363-67eb9e2e2099")],
    freePackEnabled: true,
    premiumPackEnabled: true,
    cadPackEnabled: true,
    freePdfUrl: "#",
    premiumUrl: "#",
    cadUrl: "#",
    premiumPrice: 9.99,
    cadPrice: 34.99,
    badges: ["Free Preview", "Premium PDF", "DWG", "With Terrace", "Hot Climate Friendly"],
    scores: { functionality: 90, comfort: 88, constructionSimplicity: 86, costEfficiency: 84, hotClimateAdaptation: 96, futureExtension: 82 },
    bestFor: ["African family life", "Shaded outdoor living", "Hot climates"],
    beCareful: ["Veranda orientation should suit sun path", "Check local roof detailing"],
    status: "Published",
    views: 11140
  },
  {
    id: "plan-007",
    title: "Duplex House Plan with Revit Files",
    slug: "duplex-house-plan-with-revit-files",
    reference: "MFHP-007/2026",
    shortDescription: "A two-level duplex package for professionals who need editable BIM source files.",
    description: "This duplex plan is prepared for advanced coordination, with Revit and IFC options for designers, builders and students who need editable source files.",
    category: "Revit House Plans",
    totalArea: 286,
    builtArea: 248,
    plotWidth: 18,
    plotLength: 25,
    bedrooms: 5,
    bathrooms: 5,
    livingRooms: 2,
    kitchens: 1,
    floors: 2,
    roofType: "Flat roof",
    architecturalStyle: "Modern duplex",
    foundationType: "Raft foundation",
    structureType: "Reinforced concrete frame",
    mainImage: planImage("photo-1600607688960-e095ff83135c"),
    galleryImages: [planImage("photo-1600573472550-8090b5e0745e"), planImage("photo-1600566753376-12c8ab7fb75b")],
    freePackEnabled: false,
    premiumPackEnabled: true,
    cadPackEnabled: true,
    freePdfUrl: "#",
    premiumUrl: "#",
    cadUrl: "#",
    premiumPrice: 19.99,
    cadPrice: 69.99,
    badges: ["Premium PDF", "DWG", "Revit", "IFC"],
    scores: { functionality: 91, comfort: 92, constructionSimplicity: 68, costEfficiency: 64, hotClimateAdaptation: 82, futureExtension: 76 },
    bestFor: ["Professionals", "Large families", "BIM learning", "Premium construction"],
    beCareful: ["Needs structural coordination", "Higher budget and site supervision"],
    status: "Published",
    views: 6480
  },
  {
    id: "plan-008",
    title: "Simple Rental Unit House Plan",
    slug: "simple-rental-unit-house-plan",
    reference: "MFHP-008/2026",
    shortDescription: "A repeatable rental unit plan for simple compounds and income property projects.",
    description: "A practical rental unit concept with compact services, clear access and easy repetition across a site. Useful for landlords and small developers.",
    category: "Low Cost House Plans",
    totalArea: 54,
    builtArea: 48,
    plotWidth: 8,
    plotLength: 14,
    bedrooms: 1,
    bathrooms: 1,
    livingRooms: 1,
    kitchens: 1,
    floors: 1,
    roofType: "Gable roof",
    architecturalStyle: "Simple rental",
    foundationType: "Strip foundation",
    structureType: "Block wall construction",
    mainImage: planImage("photo-1600566752355-35792bedcfea"),
    galleryImages: [planImage("photo-1600607687939-ce8a6c25118c"), planImage("photo-1600047509358-9dc75507daeb")],
    freePackEnabled: true,
    premiumPackEnabled: true,
    cadPackEnabled: true,
    freePdfUrl: "#",
    premiumUrl: "#",
    cadUrl: "#",
    premiumPrice: 6.99,
    cadPrice: 24.99,
    badges: ["Free Preview", "Premium PDF", "DWG", "Low Cost"],
    scores: { functionality: 78, comfort: 70, constructionSimplicity: 97, costEfficiency: 94, hotClimateAdaptation: 76, futureExtension: 68 },
    bestFor: ["Rental units", "Small developers", "Low cost builds"],
    beCareful: ["Compact plan", "Privacy depends on compound layout"],
    status: "Published",
    views: 8730
  }
];

export const mockPlans: Plan[] = basePlans.map((plan, index): Plan => ({
  ...plan,
  tags: plan.tags ?? plan.badges,
  livingArea: plan.livingArea ?? Math.round(plan.totalArea * 0.72),
  minPlotWidth: plan.minPlotWidth ?? plan.minimumPlotWidth ?? plan.plotWidth,
  minPlotLength: plan.minPlotLength ?? plan.minimumPlotLength ?? plan.plotLength,
  minimumPlotWidth: plan.minimumPlotWidth ?? plan.plotWidth,
  minimumPlotLength: plan.minimumPlotLength ?? plan.plotLength,
  constructionDifficulty: plan.constructionDifficulty ?? (plan.floors > 1 ? "Advanced" : plan.totalArea > 180 ? "Medium" : "Easy"),
  climateTags: plan.climateTags ?? ["Hot climate", plan.roofType.includes("Flat") ? "Dry climate" : "Humid climate"],
  specialFeatures: plan.specialFeatures ?? plan.features ?? plan.badges.filter((badge) => ["With Terrace", "Low Cost", "Future Extension Ready", "Hot Climate Friendly"].includes(badge)),
  features: plan.features ?? plan.badges.filter((badge) => ["With Terrace", "Low Cost", "Future Extension Ready", "Hot Climate Friendly"].includes(badge)),
  floorPlanImage: plan.floorPlanImage ?? plan.galleryImages[0],
  elevationImage: plan.elevationImage ?? plan.galleryImages[1],
  threeDViewImage: plan.threeDViewImage ?? plan.mainImage,
  threeDImage: plan.threeDImage ?? plan.threeDViewImage ?? plan.mainImage,
  cadPreviewImage: plan.cadPreviewImage ?? plan.galleryImages[0],
  revitPreviewImage: plan.revitPreviewImage ?? plan.galleryImages[1],
  openGraphImage: plan.openGraphImage ?? plan.mainImage,
  mainImageAlt: plan.mainImageAlt ?? `${plan.title} exterior preview`,
  galleryImageAlt: plan.galleryImageAlt ?? `${plan.title} gallery image`,
  oldPremiumPrice: plan.oldPremiumPrice ?? Math.round((plan.premiumPrice + 5) * 100) / 100,
  oldCadPrice: plan.oldCadPrice ?? (plan.cadPrice ? Math.round((plan.cadPrice + 10) * 100) / 100 : 0),
  currency: plan.currency ?? "USD",
  gumroadPremiumUrl: plan.gumroadPremiumUrl ?? "",
  gumroadCadUrl: plan.gumroadCadUrl ?? "",
  premiumPdfUrl: plan.premiumPdfUrl ?? plan.premiumUrl,
  premiumZipUrl: plan.premiumZipUrl ?? (plan.premiumPackEnabled ? `/uploads/${plan.slug}-premium-pack.zip` : ""),
  dwgFileUrl: plan.dwgFileUrl ?? (plan.cadPackEnabled ? `/uploads/${plan.slug}.dwg` : ""),
  revitFileUrl: plan.revitFileUrl ?? (plan.badges.includes("Revit") ? `/uploads/${plan.slug}.rvt` : ""),
  ifcFileUrl: plan.ifcFileUrl ?? (plan.badges.includes("IFC") ? `/uploads/${plan.slug}.ifc` : ""),
  cadZipUrl: plan.cadZipUrl ?? (plan.cadPackEnabled ? `/uploads/${plan.slug}-cad-revit.zip` : ""),
  freePackDescription: plan.freePackDescription ?? "Watermarked PDF preview for early layout review.",
  premiumPackDescription: plan.premiumPackDescription ?? "Complete PDF pack for deeper review and local adaptation.",
  cadPackDescription: plan.cadPackDescription ?? "Editable source package for architects, engineers, builders and students.",
  isWatermarked: plan.isWatermarked ?? true,
  premiumIncludedFiles: plan.premiumIncludedFiles ?? premiumFiles,
  cadIncludedFiles: plan.cadIncludedFiles ?? cadFiles,
  scores: {
    ...plan.scores,
    naturalVentilation: plan.scores.naturalVentilation ?? Math.max(68, plan.scores.hotClimateAdaptation - 4),
    familySuitability: plan.scores.familySuitability ?? Math.max(70, plan.scores.comfort - 2)
  },
  mainStrengths: plan.mainStrengths ?? ["Clear circulation", "Practical room zoning", "Good market appeal"],
  mainLimitations: plan.mainLimitations ?? plan.beCareful,
  recommendedUsers: plan.recommendedUsers ?? plan.bestFor,
  constructionNotes: plan.constructionNotes ?? "Review structure, drainage, soil and local code requirements before construction.",
  climateNotes: plan.climateNotes ?? "Orient openings, shading and roof detailing according to local sun, wind and rainfall conditions.",
  futureExtensionNotes: plan.futureExtensionNotes ?? "Future changes should be coordinated before foundation and structural work.",
  seoTitle: plan.seoTitle ?? `${plan.title} | PDF DWG Revit House Plan`,
  seoDescription: plan.seoDescription ?? plan.metaDescription ?? plan.shortDescription,
  metaDescription: plan.metaDescription ?? plan.shortDescription,
  seoKeywords: plan.seoKeywords ?? [plan.category, `${plan.bedrooms} bedroom house plan`, `${plan.plotWidth}x${plan.plotLength}m plot`],
  canonicalUrl: plan.canonicalUrl ?? `https://myfreehouseplans.com/plans/${plan.slug}`,
  focusKeyword: plan.focusKeyword ?? plan.title.toLowerCase(),
  secondaryKeywords: plan.secondaryKeywords ?? ["free house plans PDF", "DWG house plan", "Revit house plan"],
  seoScore: plan.seoScore ?? Math.min(96, 74 + index * 3),
  readinessScore: plan.readinessScore ?? Math.min(98, 78 + index * 2),
  downloads: plan.downloads ?? 420 + index * 180,
  premiumClicks: plan.premiumClicks ?? 70 + index * 28,
  cadClicks: plan.cadClicks ?? (plan.cadPackEnabled ? 35 + index * 19 : 0),
  updatedDate: plan.updatedDate ?? `May ${20 + index}, 2026`,
  createdAt: plan.createdAt ?? `2026-05-${String(10 + index).padStart(2, "0")}`,
  updatedAt: plan.updatedAt ?? `2026-05-${String(20 + index).padStart(2, "0")}`,
  publishedAt: plan.publishedAt ?? (plan.status === "Published" ? `2026-05-${String(20 + index).padStart(2, "0")}` : undefined),
  featured: plan.featured ?? index < 3,
  popular: plan.popular ?? plan.views > 9000,
  isNew: plan.isNew ?? index > 5,
  showOnHomepage: plan.showOnHomepage ?? index < 6,
  showInCategory: plan.showInCategory ?? true,
  manualRank: plan.manualRank ?? index + 1,
  categoryRank: plan.categoryRank ?? index + 1,
  homepageRank: plan.homepageRank ?? index + 1,
  faq: plan.faq ?? defaultFaq
})).map((plan) => ({
  ...plan,
  smartScore: calculateSmartScore(plan),
  seoScore: getPlanSeoScore(plan),
  readinessScore: getReadinessScore(plan),
  priorityScore: calculatePriorityScore(plan)
}));

export const getPlanBySlug = (slug: string) => mockPlans.find((plan) => plan.slug === slug);
export const publishedPlans = mockPlans.filter((plan) => plan.status === "Published").sort((a, b) => (a.manualRank ?? 9999) - (b.manualRank ?? 9999) || (b.priorityScore ?? 0) - (a.priorityScore ?? 0));
